services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: filament-plugin-dev
    container_name: filament-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - filament-network

  db:
    image: mysql:8.0
    container_name: filament-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: filament_plugin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: filament
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - filament-network

networks:
  filament-network:
    driver: bridge

volumes:
  db-data:
